name: CI

on:
  push:
    branches:
      - main
      - staging
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: native

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: |
          alejandra --check .
          statix check

      - name: Check
        run: nix flake check

      - name: Build configurations
        run: just build all bazyli
